#!/bin/sh
#
# Runs at the end of git flow standalone-story finish
#
# Positional arguments:
# $1    The friendly name of the branch
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
# $4    The name of the release this standalone-story will be merged into
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
NAME=$1
ORIGIN=$2
BRANCH=$3
RELEASE=$4

# Implement your script here.

# To terminate the git-flow action, return a non-zero exit code.
exit 0
