#!/bin/sh
#
# Runs at the end of git flow standalone-story finish
#
# Positional arguments:
# $1    The friendly name of the branch
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
# $4    The base from which this standalone-story is started
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
NAME=$1
ORIGIN=$2
BRANCH=$3
BASE=$4

if [ -f ~/.env ]; then
  . ~/.env

  if [ "$TP_USERNAME" != "" ] && [ "$TP_PASSWORD" != "" ] && [ "$TP_URL" != "" ]; then
    # Ignore everything except numbers
    STORY_NUMBER=`echo $NAME | egrep -o '[0-9]+'`
    curl --silent --user $TP_USERNAME:$TP_PASSWORD https://$TP_URL/api/v1/UserStories/$STORY_NUMBER --request POST --header "Content-Type: application/json" --data "
      {
        EntityState: {
          Id: 73
        }
      }
    " >> /tmp/git-flow.hooks.log 2>&1
  fi
fi

exit 0
