#!/bin/sh
#
# Runs at the end of git flow story finish
#
# Positional arguments:
# $1    The friendly name of the branch
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
NAME=$1
ORIGIN=$2
BRANCH=$3

if [ -f ~/.tp.credentials ]; then
  . ~/.tp.credentials
elif [ -f ~/.tp_credentials ]; then
  . ~/.tp_credentials
elif [ -f ~/.env ]; then
  . ~/.env
fi

if [ "$TP_USERNAME" != "" ] && [ "$TP_PASSWORD" != "" ] && [ "$TP_URL" != "" ]; then
  # Mark the story as done
  STORY_NUMBER=`echo $NAME | sed -E "s@[^0-9]*([0-9]+).*@\1@g"`

  # A bit messy - you have to set entitystate using the ID and the ID is different for each project.
  # So try to set the ID for both projects and one will work and the other won't
  for entitystate in 49 24
  do
    curl --silent --user $TP_USERNAME:$TP_PASSWORD https://$TP_URL/api/v1/UserStories/$STORY_NUMBER --request POST --header "Content-Type: application/json" --data "
      {
        EntityState: {
          Id: $entitystate
        }
      }
    " >> /tmp/git-flow.hooks.log 2>&1
  done
else
  echo -e "\n ** WARNING: Targetprocess user information is not configured. Skipping targetprocess updates **\n"
fi

exit 0
