#!/bin/sh
#
# Runs at the end of git flow feature start
#
# Positional arguments:
# $1    The friendly name of the branch
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
# $4    The base from which this feature is started
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
NAME=$1
ORIGIN=$2
BRANCH=$3
BASE=$4

if [ -f ~/.tp.credentials ]; then
  . ~/.tp.credentials
elif [ -f ~/.tp_credentials ]; then
  . ~/.tp_credentials
elif [ -f ~/.env ]; then
  . ~/.env
fi

if [ "$TP_USERNAME" != "" ] && [ "$TP_PASSWORD" != "" ] && [ "$TP_URL" != "" ]; then
  # Mark the feature as pending
  FEATURE_NUMBER=`echo $NAME | sed -E "s@[^0-9]*([0-9]+).*@\1@g"`

  # A bit messy - you have to set entitystate using the ID and the ID is different for each project.
  # So try to set the ID for both projects and one will work and the other won't
  for entitystate in 58 38
  do
    curl --silent --user $TP_USERNAME:$TP_PASSWORD https://$TP_URL/api/v1/Features/$FEATURE_NUMBER --request POST --header "Content-Type: application/json" --data "
      {
        EntityState: {
          Id: $entitystate
        }
      }
    " >> /tmp/git-flow.hooks.log 2>&1
  done

  # Find the TP User Id of my user
  USER_ID="`curl --silent --user $TP_USERNAME:$TP_PASSWORD https://$TP_URL/api/v1/Users -d "where=Login eq '$TP_USERNAME'" --request GET --header "Accept: application/json" | egrep '"Id"' | head -1 | sed -E "s@[^0-9]*([0-9]+).*@\1@g"`"

  if [ "$USER_ID" != "" ]
  then
    # Assign current user to feature as a developer
    curl --silent --user $TP_USERNAME:$TP_PASSWORD https://$TP_URL/api/v1/Features/$FEATURE_NUMBER/Assignments --header "Content-Type: application/json" --data "
      [
        {
          GeneralUser: {
            Id: $USER_ID
          },
          Role: {
            Id: 1
          }
        }
      ]
    " >> /tmp/git-flow.hooks.log 2>&1
  fi
else
  echo -e "\n ** WARNING: Targetprocess user information is not configured. Skipping targetprocess updates **\n"
fi

exit 0
