#!/bin/sh
#
# Runs at the end of git flow feature finish
#
# Positional arguments:
# $1    The friendly name of the branch
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
# $4    The name of the release this feature will be merged into
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
NAME=$1
ORIGIN=$2
BRANCH=$3
RELEASE=$4

if [ -f ~/.env ]; then
  . ~/.env
fi

if [ "$TP_USERNAME" != "" ] && [ "$TP_PASSWORD" != "" ] && [ "$TP_URL" != "" ]; then
  # Mark the feature as qa pending
  FEATURE_NUMBER=`echo $NAME | sed -E "s@[^0-9]*([0-9]+).*@\1@g"`
  curl --silent --user $TP_USERNAME:$TP_PASSWORD https://$TP_URL/api/v1/Features/$FEATURE_NUMBER --request POST --header "Content-Type: application/json" --data "
    {
      EntityState: {
        Id: 98
      }
    }
  " >> /tmp/git-flow.hooks.log 2>&1

  # Add the feature to the release it was merged into
  RELEASE_ID="`curl --silent --user $TP_USERNAME:$TP_PASSWORD https://$TP_URL/api/v1/Releases -d "where=Name eq '$RELEASE'" --request GET --header "Accept: application/json" | egrep '"Id"' | head -1 | sed -E "s@[^0-9]*([0-9]+).*@\1@g"`"

  if [ "$RELEASE_ID" != "" ]
  then
    # Update the feature's release
    curl --silent --user $TP_USERNAME:$TP_PASSWORD https://$TP_URL/api/v1/Features/$FEATURE_NUMBER --header "Content-Type: application/json" --data "
      {
        Release: {Id: $RELEASE_ID}
      }
    " >> /tmp/git-flow.hooks.log 2>&1
  fi
else
  echo -e "\n ** WARNING: Targetprocess user information is not configured. Skipping targetprocess updates **\n"
fi

exit 0
