#!/bin/sh
#
# Runs before git flow story start
#
# Positional arguments:
# $1    The friendly name of the branch
# $2    The origin remote
# $3    The full branch name (including the story prefix)
# $4    The base from which this story is started
# $5    The feature the story is associated with
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
NAME=$1
ORIGIN=$2
BRANCH=$3
BASE=$4
FEATURE=$5

# Implement your script here.

# To terminate the git-flow action, return a non-zero exit code.
exit 0
